#!/bin/bash

find -name '*.h' -o -name '*.cc' | xargs sed -i 's/bse_/REFLECTION_BASE_CLASS/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/bse__/REFLECTION_BASE_CLASS_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/abt__/REFLECTION_CLASS/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/col_/REFLECTION_COLLECTION/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/ctr_/REFLECTION_CONSTRUCTOR/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/ctr__/REFLECTION_CONSTRUCTOR_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/fcn_/REFLECTION_FACTORY_NAME/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/fct_/REFLECTION_FACTORY/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/mth_/REFLECTION_METHOD/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/mth__/REFLECTION_METHOD_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/mto_/REFLECTION_OVERLOADED_METHOD/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/mto__/REFLECTION_OVERLOADED_METHOD_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/mtc_/REFLECTION_OVERLOADED_CONST_METHOD/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/mtc__/REFLECTION_OVERLOADED_CONST_METHOD_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/stt_/REFLECTION_SETTER/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/stt__/REFLECTION_SETTER_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/end_/REFLECTION_END/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/end__/REFLECTION_END_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/endt_/REFLECTION_END_TOKEN/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/endt__/REFLECTION_END_TOKEN_/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/tbg_/REFLECTION_TEMPLATE_BEGIN/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/tpl__/REFLECTION_TEMPLATE/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/ten_/REFLECTION_TEMPLATE_END/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/prp_/REFLECTION_FIELD_VALUE_INPLACE/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/pre_/REFLECTION_FIELD_ENUM_INPLACE/'
find -name '*.h' -o -name '*.cc' | xargs sed -i 's/prr_/REFLECTION_FIELD_REFERENCE_INPLACE/'

